//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpend_iCryService
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance
    {
        public string account_id { get; set; }
        public string curency { get; set; }
        public decimal available { get; set; }
        public decimal current { get; set; }
        public System.DateTime update_timestamp { get; set; }
        public bool requires_notification { get; set; }
    }
}
