//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpend_iCryService
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public string transaction_id { get; set; }
        public string account_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public string description { get; set; }
        public string transaction_category { get; set; }
        public decimal amount { get; set; }
        public string currency { get; set; }
        public string meta_provider_transaction_category { get; set; }
        public string meta_transaction_reference { get; set; }
        public string transaction_type { get; set; }
    }
}
